In [ ]:
 import torch
 import numpy as np

 import pandas as pd
 

# Trabajando con tensores

In [ ]:
torch.__version__

'1.8.1+cu101'

In [ ]:
tensor_a = torch.ones(2, 2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
tensor_b = torch.Tensor(2, 2)
print(tensor_b)
tensor_b.uniform_(0,1)

tensor([[3.5519e-20, 3.0792e-41],
        [3.7835e-44, 0.0000e+00]])


tensor([[0.0146, 0.0112],
        [0.9462, 0.4152]])

In [ ]:
tensor_c = torch.rand(2,2)
tensor_c

tensor([[0.6334, 0.8862],
        [0.8692, 0.4536]])

In [ ]:
result = tensor_b + tensor_c
result

tensor([[0.6479, 0.8974],
        [1.8154, 0.8689]])

In [ ]:
result.shape
reshaped = result.view(4,1)
reshaped

tensor([[0.6479],
        [0.8974],
        [1.8154],
        [0.8689]])

In [ ]:
points = torch.tensor([[1.0, 2.0],[3.0, 4.0]])
print(points)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
points.storage()

 1.0
 2.0
 3.0
 4.0
[torch.FloatStorage of size 4]

In [ ]:
points, points.stride()

(tensor([[1., 2.],
         [3., 4.]]), (2, 1))

In [ ]:
p_t = points.t()
p_t

tensor([[1., 3.],
        [2., 4.]])

In [ ]:
tensor_x = torch.tensor([1, 2, 3, 4])
tensor_x, torch.unsqueeze(tensor_x, 1)

(tensor([1, 2, 3, 4]), tensor([[1],
         [2],
         [3],
         [4]]))

In [ ]:
numpyArray = np.random.randn(2,2)
from_numpy = torch.from_numpy(numpyArray)
from_numpy

tensor([[ 0.3767,  0.7844],
        [-1.9967, -0.2245]], dtype=torch.float64)

# Representar datos con tensores

In [ ]:
print(from_numpy)
print(torch.mean(from_numpy))
print(torch.mean(from_numpy, dim=0))
print(torch.mean(from_numpy, dim=1))

tensor([[ 0.3767,  0.7844],
        [-1.9967, -0.2245]], dtype=torch.float64)
tensor(-0.2650, dtype=torch.float64)
tensor([-0.8100,  0.2800], dtype=torch.float64)
tensor([ 0.5806, -1.1106], dtype=torch.float64)


In [ ]:
torch.std(from_numpy, dim=1)

tensor([0.2883, 1.2531], dtype=torch.float64)

In [ ]:
torch.save(from_numpy, 'tensor.t')

In [ ]:
load = torch.load('tensor.t')
load

tensor([[ 0.3767,  0.7844],
        [-1.9967, -0.2245]], dtype=torch.float64)

In [ ]:
url = 'https://raw.githubusercontent.com/amanthedorkknight/fifa18-all-player-statistics/master/2019/data.csv'
dataframe = pd.read_csv(url)
dataframe

Unnamed: 0      ID  ... GKReflexes  Release Clause
0               0  158023  ...        8.0         €226.5M
1               1   20801  ...       11.0         €127.1M
2               2  190871  ...       11.0         €228.1M
3               3  193080  ...       94.0         €138.6M
4               4  192985  ...       13.0         €196.4M
...           ...     ...  ...        ...             ...
18202       18202  238813  ...        9.0           €143K
18203       18203  243165  ...       12.0           €113K
18204       18204  241638  ...       13.0           €165K
18205       18205  246268  ...        9.0           €143K
18206       18206  246269  ...        9.0           €165K

[18207 rows x 89 columns]

In [ ]:
dataframe.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingT

In [ ]:
subset = dataframe[['Overall', 'Age', 'International Reputation', 'Weak Foot','Skill Moves']].dropna(axis=0, how='any')
columns = subset.columns[1:]
players = torch.tensor(subset.values).float()
players.shape, players.type()

(torch.Size([18159, 5]), 'torch.FloatTensor')

In [ ]:
data = players[:, 1:]
data, data.shape

(tensor([[31.,  5.,  4.,  4.],
         [33.,  5.,  4.,  5.],
         [26.,  5.,  5.,  5.],
         ...,
         [16.,  1.,  3.,  2.],
         [17.,  1.,  3.,  2.],
         [16.,  1.,  3.,  2.]]), torch.Size([18159, 4]))

In [ ]:
target = players[:, 0]
target, target.shape

(tensor([94., 94., 92.,  ..., 47., 47., 46.]), torch.Size([18159]))

In [ ]:
mean = torch.mean(data, dim=0)
mean

tensor([25.1225,  1.1132,  2.9473,  2.3613])

In [ ]:
std = torch.std(data, dim=0)
std

tensor([4.6706, 0.3940, 0.6605, 0.7562])

In [ ]:
norm = (data - mean)/torch.sqrt(std)
norm

tensor([[ 2.7196,  6.1919,  1.2953,  1.8845],
        [ 3.6450,  6.1919,  1.2953,  3.0345],
        [ 0.4060,  6.1919,  2.5258,  3.0345],
        ...,
        [-4.2211, -0.1804,  0.0648, -0.4155],
        [-3.7584, -0.1804,  0.0648, -0.4155],
        [-4.2211, -0.1804,  0.0648, -0.4155]])

In [ ]:
good = data[torch.ge(target, 85)]
average = data[torch.gt(target, 70) & torch.lt(target,85)]
notSoGood = data[torch.lt(target, 70)]

goodMean = torch.mean(good, dim=0)
averageMean = torch.mean(average, dim=0)
notSoGoodMean = torch.mean(notSoGood, dim=0)

goodMean, averageMean, notSoGoodMean

(tensor([28.3455,  3.3818,  3.4455,  3.0364]),
 tensor([27.2285,  1.3561,  3.1114,  2.7515]),
 tensor([24.1909,  1.0079,  2.8795,  2.1952]))

In [ ]:
for i, args in enumerate(zip(columns, goodMean, averageMean, notSoGoodMean)):
  print('{:25} {:6.2f} {:6.2f} {:6.2f}'.format(*args))

Age                        28.35  27.23  24.19
International Reputation    3.38   1.36   1.01
Weak Foot                   3.45   3.11   2.88
Skill Moves                 3.04   2.75   2.20
